import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String = "8.2.0"

    const val retrofit2_kotlinx_serialization_converter: String = "0.4.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1"

    const val com_gradle_build_scan_gradle_plugin: String = "2.4.1" // available: "2.4.2"

    const val com_android_tools_build_gradle: String = "3.5.0"

    const val kotlinx_serialization_runtime: String = "0.13.0"

    const val kotlinx_coroutines_android: String = "1.3.1"

    const val kotlinx_coroutines_core: String = "1.3.1"

    const val kotlinx_coroutines_test: String = "1.3.1"

    const val lifecycle_viewmodel_ktx: String = "2.1.0"

    const val androidx_test_espresso: String = "3.2.0"

    const val de_mannodermaus_junit5: String = "1.1.0"

    const val junit_vintage_engine: String = "5.5.2"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val logging_interceptor: String = "4.2.0"

    const val legacy_support_v4: String = "1.0.0"

    const val org_junit_jupiter: String = "5.5.2"

    const val constraintlayout: String = "1.1.3"

    const val android_junit5: String = "1.5.1.0"

    const val preference_ktx: String = "1.1.0"

    const val androidx_room: String = "2.1.0"

    const val androidx_test: String = "1.2.0"

    const val javax_inject: String = "1"

    const val recyclerview: String = "1.0.0"

    const val androidclog: String = "2.0.7"

    const val lint_gradle: String = "26.5.0"

    const val robolectric: String = "4.3"

    const val strikt_core: String = "0.22.1"

    const val threetenabp: String = "1.2.1"

    const val annotation: String = "1.1.0"

    const val threetenbp: String = "1.4.0"

    const val appcompat: String = "1.1.0"

    const val debug_db: String = "1.0.6"

    const val material: String = "1.0.0"

    const val org_koin: String = "2.0.1"

    const val retrofit: String = "2.6.1"

    const val barista: String = "3.2.0"

    const val browser: String = "1.0.0"

    const val common: String = "1.11.4"

    const val jsr305: String = "3.0.2"

    const val ktlint: String = "0.33.0" // available: "0.34.2"

    const val aapt2: String = "3.5.0-5435860"

    const val junit: String = "1.1.1"

    const val mockk: String = "1.9.3"

    const val coil: String = "0.7.0"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
